// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThuVienMedia.Data;

#nullable disable

namespace ThuVienMedia.Migrations
{
    [DbContext(typeof(ThuVienDbContext))]
    partial class ThuVienDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThuVienMedia.Models.CMThuVienMedia", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChuyenMucCapChaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IDChuyenMucCapCha")
                        .HasMaxLength(40)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("SuDung")
                        .HasColumnType("bit");

                    b.Property<string>("TenChuyenMuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("ThuTuSapXep")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("ChuyenMucCapChaID");

                    b.ToTable("CMThuVienMedia", (string)null);
                });

            modelBuilder.Entity("ThuVienMedia.Models.FileMedia", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IDThuVienMedia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdFile")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("LoaiFile")
                        .HasColumnType("tinyint");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<byte?>("NguonFile")
                        .HasColumnType("tinyint");

                    b.Property<string>("OwnerCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TacGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("ThuTuSapXep")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("ThuVienMediaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlAnhDaiDienVideo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UrlFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UrlThumb")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("IDThuVienMedia");

                    b.HasIndex("ThuVienMediaID");

                    b.ToTable("FileMedia", (string)null);
                });

            modelBuilder.Entity("ThuVienMedia.Models.ThuVienMediaModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChuyenMucMediaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GioiThieu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("IDChuyenMucMedia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IDFileMediaList")
                        .HasColumnType("varchar(MAX)");

                    b.Property<int?>("LastModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("LoaiThuVien")
                        .HasColumnType("tinyint");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("SuDung")
                        .HasColumnType("bit");

                    b.Property<string>("TenThuVien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("ThuTuSapXep")
                        .HasColumnType("tinyint");

                    b.Property<string>("UrlAnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UrlThumbAnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("ChuyenMucMediaID");

                    b.ToTable("ThuVienMedia", (string)null);
                });

            modelBuilder.Entity("ThuVienMedia.Models.CMThuVienMedia", b =>
                {
                    b.HasOne("ThuVienMedia.Models.CMThuVienMedia", "ChuyenMucCapCha")
                        .WithMany("ChuyenMucCons")
                        .HasForeignKey("ChuyenMucCapChaID");

                    b.Navigation("ChuyenMucCapCha");
                });

            modelBuilder.Entity("ThuVienMedia.Models.FileMedia", b =>
                {
                    b.HasOne("ThuVienMedia.Models.ThuVienMediaModel", null)
                        .WithMany()
                        .HasForeignKey("IDThuVienMedia")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThuVienMedia.Models.ThuVienMediaModel", "ThuVienMedia")
                        .WithMany("Files")
                        .HasForeignKey("ThuVienMediaID");

                    b.Navigation("ThuVienMedia");
                });

            modelBuilder.Entity("ThuVienMedia.Models.ThuVienMediaModel", b =>
                {
                    b.HasOne("ThuVienMedia.Models.CMThuVienMedia", "ChuyenMucMedia")
                        .WithMany("ThuVienMedias")
                        .HasForeignKey("ChuyenMucMediaID");

                    b.Navigation("ChuyenMucMedia");
                });

            modelBuilder.Entity("ThuVienMedia.Models.CMThuVienMedia", b =>
                {
                    b.Navigation("ChuyenMucCons");

                    b.Navigation("ThuVienMedias");
                });

            modelBuilder.Entity("ThuVienMedia.Models.ThuVienMediaModel", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
